---
  - name: restart nginx
    become: True
    service:
      name: nginx
      enabled: yes
      state: restarted

  - name: restart grafana
    become: True
    service:
      name: grafana-server
      enabled: yes
      state: restarted
