---
- name: Restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: restarted

- name: Restart grafana
  become: true
  ansible.builtin.service:
    name: grafana-server
    enabled: true
    state: restarted
